SOUTH, NORTH, EAST, WEST, PICKUP = 0, 1, 2, 3, 4
ACTIONS = [SOUTH, NORTH, EAST, WEST, PICKUP]

STEP_REWARD, APPLE_PICKUP_REWARD, BAD_APPLE_PICKUP_REWARD, STEP_INTO_THORN_REWARD = "step", "good_pickup", "bad_pickup", "step_into_thorn"
REWARD_DICT = {STEP_REWARD: -1, APPLE_PICKUP_REWARD: 10, BAD_APPLE_PICKUP_REWARD: -10, STEP_INTO_THORN_REWARD: -5}

MAX_APPLE_NUM = sum([1, 2, 3, 4])

DETERMINISTIC_PROB = 1.0
STOCHASTIC_PROB = 0.91
STOCHASTIC_PROB_OTHER_ACTIONS = (DETERMINISTIC_PROB - STOCHASTIC_PROB) / 3